project_name: aegis

builds:
  - binary: aegis
    main: .
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/nmashchenko/aegis-cli/cmd.Version={{ .Tag }}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
